## @(#) : textlint prh dictionary / atsushifx's add-on rules
#
# @version  1.0.0
# @author   atsushifx <https://github.com/atsushifx>
# @since    2025-01-31
# @license  MIT
#
# @desc<<
#
# textlint prh base dictionary
#
#<<

## dict start
rules:
