## @(#) : textlint prh dictionary / atsushifx's add-on
#
# @version 1.0.0
# @author  Furukawa, Atsushi <atsushifx@gmail.com>
# @date    2025-01-31
# @license MIT
#
# @desc<<
#
# textlint prh base dictionary
#
#<<

## dict start
rules:
