## @(#) : textlint prh dictionary
#
# @version  1.0.0
# @author   atsushifx <https://github.com/atsushifx>
# @since    2025-01-31
# @license  MIT
#
# @desc<<
#
# textlint prh base dictionary
#
#<<

version: 1
#
imports:
  ## smarthr proofreading dictionary
  - ./smarthr/prh-idiomatic-usage.yml
  ## atsushifx's add-on
  - ./prh-atsushifx.yml
