# src: ./configs/betterleaks.toml
# @(#) : betterleaks configuration for secret detection
#
# Copyright (c) 2026- atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

title = "BetterLeaks config"

minVersion = "v8.25.0"              #  gitleaks min version
betterleaksMinVersion = "v1.0.0"
