# src: ./codegpt.config.yaml
# @(#) : CodeGPT config for commit message
#
# Copyright (c) 2025 atsushifx <http://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

openai:
  provider: "openai"
  model: gpt-4o

output:
  lang: ja
