# src: ./configs/gitleaks.toml
# @(#) : gitleaks configuration for secret detection
#
# Copyright (c) 2025 atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

title = "Gitleaks config"

[[allowlists]]
description = "Exclude common large or irrelevant directories"
paths = [
  "node_modules/",
  ".git/",
  "dist",
	"lib",
	"maps",
	"module",
  ".cache/",
  "pnpm-lock.yaml",
]

# ======================
# Rules: built-in rules + 強化版
# ======================
