# src: ./configs/gitleaks.toml
# @(#) : gitleaks configuration for secret detection
#
# Copyright (c) 2025 atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

title = "Gitleaks config"

[[allowlists]]
description = "Exclude common large or irrelevant directories"
paths = [
  "node_modules/",
  ".git/",
  "dist",
	"lib",
	"maps",
	"module",
  ".cache/",
  "pnpm-lock.yaml",
]


# ======================
# Rules: built-in rules + 強化版
# ======================
[[allowlists]]
description = "Ignore safe config keywords"
regexes = [
  	'''https''',
	'''config.base''',
	'''.textlint''',
	'''configs''',
	'''markdown''',
	'''.github''',
	'''dprint.dev''',
	'''conventionalcommits''',
	'''contributor-covenant.org''',
	#
	'''.cache/''',
	'''tsbuild-cache''',
	# textlint
	'''textlint-rule''',
	'''ja-technical-writing''',
	'''no-mixed-zenkaku-and-hankaku-alphabet''',
	'''ja-space-between-half-and-full-width''',
	# source code
	'''AglaError''',
	'''allowConciseArrowFunctionExpressionsStartingWithVoid''',
	'''shared/types''',
	#
	'''claude/''',
	'''typescript''',
	'''integration''',
	'''spec.ts''',
	'''PSScriptRoot''',
	'''internal-docs/''',
]
[[rules]]
id = "high-entropy"
description = "Strict High Entropy String Rule"
regex = '''[A-Za-z0-9+-/\\=]{35,}'''
entropy = 3.7
tags = ["entropy", "generic"]
