# src: ./configs/gitleaks.toml
# @(#) : detect generic API key
#
# @version	1.0.0
# @since	2025-05-05
# @author	atsushifx <https://github.com/atsushifx>
#
# @description<<
#
# secrets 検出ルールを追加・調整する場合は [[rules]] セクションを編集してください。
#
#<<

title = "Gitleaks config"

[[allowlists]]
paths = [
	"'''node_modules/.*'''"
]

level = "warn"
redact = true

[detect]
secrets = true
entropy = true

[[rules]]
id = "github-token"
description = "GitHub Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["key", "GitHub"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(?-i)['"][0-9a-zA-Z/+]{40}['"]'''
tags = ["key", "AWS"]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key)(.{0,20})?['"][0-9a-zA-Z]{16,45}['"]'''
tags = ["key", "generic"]

[[rules]]
id = "password-variable"
description = "Generic password variable"
regex = '''(?i)(password|passwd|pwd)['"]?\s*[:=]\s*['"].{6,}['"]'''
tags = ["password", "generic"]
