# src: ./configs/secretlintrc.yaml
### @(#) : secretlintrc
#
# @version  1.0.0
# @author   atsushifx <https://github.com/atsushifx>
# @since    2025-04-15
# @license  MIT
#
# @description<<
#
# Configuration for secretlint to detect secrets in source code.
# Applies the "@secretlint/secretlint-rule-preset-recommend" preset for best practices.
# Ensures sensitive data like API keys are not accidentally exposed.
#
#<<

rules:
  - id: "@secretlint/secretlint-rule-preset-recommend"
