# src: .github/workflows/ci-lint.yaml
## @(#) : ci-lint / lint new articles
#
# @version  1.0.2
# @author   Furukawa Atsushi <atsushifx@gmail.com>
# @since    2025-02-05
# @license  MIT
#
# @desc<<
#
# lint new articles on GitHub
#
#<<

name: ci-lint

# PR及び手動でAction実行
on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
  workflow_dispatch:

# 実行するAction
jobs:
  lint-on-github:
    name: lint on github
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Fetch main repository
        run: |
          git fetch origin main

      - name: Get changed Markdown files
        id: changed-md
        run: |
          head_sha="$(git rev-parse HEAD)"
          base_sha="$(git rev-parse origin/main)"

          files=$(git diff --diff-filter=AM --name-only "${base_sha}" "${head_sha}" -- '**/*.md')
          printf "changed:\n%s\n" "$files"

          {
            echo "files<<EOF"
            echo "$files"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-cache
          path: |
            node_modules
            ~/.pnpm-store
            .cache/*

      - name: Install linters
        if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
        run: |
          chmod +x ./scripts/ag-install-linter.sh
          ./scripts/ag-install-linter.sh "--save-prod --reporter silent "
          pnpm list

      - name: Lint text
        if: ${{ steps.changed-md.outputs.files != '' }}
        env:
          changed_files: "${{ steps.changed-md.outputs.files }}"
        run: |
          pnpm run lint:text "${changed_files}"

      - name: Lint markdown
        if: ${{ steps.changed-md.outputs.files != '' }}
        env:
          changed_files: "${{ steps.changed-md.outputs.files }}"
        run: |
          pnpm run lint:markdown "${changed_files}"

      - name: Always save cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
          path: |
            node_modules
            ~/.pnpm-store
            .cache/*
