# src: ./.github/workflows/ci-scan-secrets.yml
# @(#) : Caller workflow for secret scanning in .github repository
#
# Copyright (c) 2025- atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "CI Scan Secrets"

# Minimal permissions following security best practices
permissions:
  contents: read

on:
  push:

  pull_request:
    branches:
      - main
      - master
      - releases

  workflow_dispatch:

jobs:
  scan-betterleaks:
    name: Betterleaks Secret Scan
    permissions:
      contents: read
    uses: aglabo/ci-platform/.github/workflows/ci-scan-betterleaks.yml@2ac45debcb9c2902597abda02bcce3e6ff0121f0 # v0.2.1
