# src: ./.github/workflows/ci-workflows-qa.yml
# @(#) : Caller workflow for GitHub Actions workflow QA in .github repository
#
# Copyright (c) 2025- atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "CI Workflows QA"

# Minimal permissions following security best practices
permissions:
  contents: read

on:
  push:
    branches:
      - main
      - master
      - releases

  pull_request:
    branches:
      - main
      - master
      - releases

  workflow_dispatch:

jobs:
  actionlint:
    name: Actionlint
    permissions:
      contents: read
    uses: aglabo/ci-platform/.github/workflows/ci-qa-actionlint.yml@2ac45debcb9c2902597abda02bcce3e6ff0121f0 # v0.2.1

  ghalint:
    name: Ghalint
    permissions:
      contents: read
    uses: aglabo/ci-platform/.github/workflows/ci-qa-ghalint.yml@2ac45debcb9c2902597abda02bcce3e6ff0121f0 # v0.2.1
